import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Text, TouchableOpacity, View, ScrollView, StyleSheet, Linking } from "react-native";


const Section = ({ title, children }) => (
  <View style={styles.section}>
    <Text style={styles.heading}>{title}</Text>
    {children}
  </View>
);

export default function PrivacyPolicScreen() {
  return (

      <ScrollView style={styles.container}>
      <TouchableOpacity onPress={() => router.back()}>
        <Ionicons size={28} name="arrow-back-outline" color="#000" />
      </TouchableOpacity>
      <Text style={styles.title}>Privacy Policy</Text>
     
      <Text style={styles.paragraph}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </Text>

      <Text style={styles.paragraph}>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. 
        .
      </Text>

      <Section title="Interpretation and Definitions">
        <Text style={styles.subHeading}>Interpretation</Text>
        <Text style={styles.paragraph}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Text>

        <Text style={styles.subHeading}>Definitions</Text>
        <Text style={styles.paragraph}>
          For the purposes of this Privacy Policy:
        </Text>

        <View style={styles.list}>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Account</Text> means a unique account
            created for You to access our Service or parts of our Service.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Application</Text> refers to Triathlon
            Forge, the software program provided by the Company.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Company</Text> refers to Triathlon Forge
            (referred to as &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;).
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Country</Text> refers to: Serbia
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Device</Text> means any device that can
            access the Service.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Personal Data</Text> is any information
            that relates to an identified or identifiable individual.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Service</Text> refers to the
            Application.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>Usage Data</Text> refers to data
            collected automatically, either generated by the use of the Service
            or from the Service infrastructure itself.
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>You</Text> means the individual
            accessing or using the Service.
          </Text>
        </View>
      </Section>

      <Section title="Collecting and Using Your Personal Data">
        <Text style={styles.subHeading}>Types of Data Collected</Text>
        <Text style={styles.subSubHeading}>Personal Data</Text>
        <Text style={styles.paragraph}>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information such as:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Email address</Text>
          <Text style={styles.listItem}>• First name and last name</Text>
          <Text style={styles.listItem}>• Usage Data</Text>
        </View>

        <Text style={styles.subSubHeading}>Usage Data</Text>
        <Text style={styles.paragraph}>
          Usage Data is collected automatically when using the Service. It may
          include IP address, browser type, version, pages visited, time spent,
          unique device identifiers and other diagnostic data.
        </Text>
      </Section>

      <Section title="Use of Your Personal Data">
        <View style={styles.list}>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>To provide and maintain our Service</Text>
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>To manage Your Account</Text>
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>For the performance of a contract</Text>
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>To contact You</Text>
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>To provide You with offers</Text>
          </Text>
          <Text style={styles.listItem}>
            • <Text style={styles.bold}>To manage Your requests</Text>
          </Text>
        </View>
      </Section>

      <Section title="Children's Privacy">
        <Text style={styles.paragraph}>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from children
          under 13. If You are a parent or guardian and become aware that Your
          child has provided Us with Personal Data, please contact Us.
        </Text>
      </Section>

      <Section title="Links to Other Websites">
        <Text style={styles.paragraph}>
          Our Service may contain links to other websites that are not operated
          by Us. We strongly advise You to review the Privacy Policy of every
          site You visit.
        </Text>
      </Section>

      <Section title="Changes to this Privacy Policy">
        <Text style={styles.paragraph}>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date.
        </Text>
      </Section>

      <Section title="Contact Us">
        <Text style={styles.paragraph}>
          If you have any questions, You can contact us:
        </Text>
        <View style={styles.list}>
          <Text
            style={styles.link}
            onPress={() => Linking.openURL("mailto:info@triathlonforge.com")}
          >
            • By email: app@triathlonforge.com
          </Text>
          <Text
            style={styles.link}
            onPress={() => Linking.openURL("https://triathlonForge.com/contact")}
          >
            • By visiting: triathlonForge.com
          </Text>
        </View>
      </Section>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#333",
  },
  date: {
    fontSize: 14,
    color: "#666",
    marginBottom: 16,
  },
  section: {
    marginBottom: 24,
  },
  heading: {
    fontSize: 20,
    fontWeight: "600",
    color: "#222",
    marginBottom: 6,
  },
  subHeading: {
    fontSize: 18,
    fontWeight: "500",
    marginTop: 8,
    color: "#444",
  },
  subSubHeading: {
    fontSize: 16,
    fontWeight: "500",
    marginTop: 6,
    color: "#555",
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 22,
    color: "#555",
    marginBottom: 6,
  },
  bold: {
    fontWeight: "600",
    color: "#333",
  },
  list: {
    marginLeft: 12,
    marginTop: 4,
  },
  listItem: {
    fontSize: 15,
    lineHeight: 22,
    color: "#555",
    marginBottom: 4,
  },
  link: {
    color: "#007AFF",
    textDecorationLine: "underline",
    marginBottom: 6,
    fontSize: 15,
  },
});
